package share.apk.server.management;

public enum ServerResult {
	SUCCESS, INVALID_INPUT, INSUFFICIENT_INPUT, ERROR, EXCEPTION, SESSION_STARTED, SESSION_DESTROYED, INVALID_SESSION, INVALID_HTTP_REQUEST_METHOD;
}
